/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-16 02:18:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.host;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.triby.host.model.vo.Host;

public final class hiddenIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/host/header.jsp", Long.valueOf(1570963706000L));
    _jspx_dependants.put("/views/host/aside.jsp", Long.valueOf(1570791286000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.triby.host.model.vo.Host");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody{height:100%; overflow:auto;}\r\n");
      out.write("\t#content{\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\tmargin: 1%;\r\n");
      out.write("\t\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t\twidth:80%;\r\n");
      out.write("\t\theight:90vh;\r\n");
      out.write("\t}\r\n");
      out.write("\t#div1, #div2, #div4{\r\n");
      out.write("\t\twidth:40%;\r\n");
      out.write("\t\theight:250px;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\tmargin: 25px 25px 25px 55px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#div3{\r\n");
      out.write("\t\twidth:40%;\r\n");
      out.write("\t\theight:250px;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\tmargin: 25px 25px 25px 55px;\r\n");
      out.write("\t\tclear:both;\r\n");
      out.write("\t}\r\n");
      out.write("\t#card-body1, #card-body3, #card-body4{text-align:center;}\r\n");
      out.write("\t#card-body1 h4, #card-body1 p{\r\n");
      out.write("\t\theight: 40%;\r\n");
      out.write("\t\tline-height: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#inform-modify, #notice-detail{\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t\tfont-size:12px;\r\n");
      out.write("\t\tcolor:gray;\r\n");
      out.write("\t}\r\n");
      out.write("\t#inform-modify:hover, #notice-detail:hover{cursor:pointer;}\r\n");
      out.write("\t#notice-detail+div{font-size:18px; font-weight:bold;}\r\n");
      out.write("\t#noticeTb{clear:both; margin-top:20px;}\r\n");
      out.write("\t.table tr td{font-size:15px; font-weight:bold;}\r\n");
      out.write("\t#informTb tr:nth-child(2n), #calculateTb tr:nth-child(2n){font-size:18px;}\r\n");
      out.write("\t#informTb tr:nth-child(1), #informTb tr:nth-child(3), #calculateTb tr:nth-child(1), #calculateTb tr:nth-child(3){font-size:12px; color:gray;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
 String contextPath = request.getContextPath(); 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody{height:100%; overflow:auto;}\r\n");
      out.write("\t#aside{\r\n");
      out.write("\t\twidth:18%;\r\n");
      out.write("\t\theight:100vh;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\t#triby-manage, #member-manage{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.none-bullet{list-style-type: none;}\r\n");
      out.write("\tli{margin-top:10px;}\r\n");
      out.write("\tli a{\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t}\r\n");
      out.write("\tli a:hover{\r\n");
      out.write("\t\ttext-decoration:underline;\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#list-header{font-size:18px;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">");
      out.write('\r');
      out.write('\n');
 
	Host loginHost = (Host) session.getAttribute("loginHost");
	String joinSuccessMsg = (String)request.getAttribute("joinSuccessMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/popper.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/bootstrap.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar joinSuccessMsg = \"");
      out.print(joinSuccessMsg);
      out.write("\"\r\n");
      out.write("$(function(){\r\n");
      out.write("\tif(joinSuccessMsg!=\"null\"){\r\n");
      out.write("\talert(joinSuccessMsg);\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body{height:100%; overflow:hidden;}\r\n");
      out.write("\t#wrapper{\r\n");
      out.write("    height: 10%;\r\n");
      out.write("    overflow:hidden;\r\n");
      out.write("    font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t} \r\n");
      out.write("\t#logo-wrap{\r\n");
      out.write("\t\twidth:15%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logo{\r\n");
      out.write("\t\tmargin-left: auto;\r\n");
      out.write("\t\tmargin-right:auto;\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\theight:60px;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\tlabel{\r\n");
      out.write("\t\tmargin-left:1%;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\twidth:50%;\r\n");
      out.write("\t\tline-height: 50px;\r\n");
      out.write("\t\tmargin-top: auto;\r\n");
      out.write("\t\tmargin-bottom: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t#lb2{\r\n");
      out.write("\t\twidth:27%;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\ttext-align:right;\r\n");
      out.write("\t\tline-height: 50px;\r\n");
      out.write("\t\tmargin-right:1%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logout{\r\n");
      out.write("\t\tmargin-left:2%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logo:hover{cursor:pointer;}\r\n");
      out.write("</style>\r\n");
      out.write("<title>관리자 페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("<div id=\"header\" class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\r\n");
      out.write("  <div id=\"logo-wrap\"><div id=\"logo\" onclick=\"goIndex();\"><img src=\"resources/images/triby5.png\"></div></div>\r\n");
      out.write("  <label>호스트 관리페이지</label>\r\n");
      out.write("   <div id=\"lb2\">");
      out.print( loginHost.getHost_name() );
      out.write(" 호스트님 반갑습니다!</div>\r\n");
      out.write("  <div id=\"logout\"><a href=\"");
      out.print( request.getContextPath());
      out.write("/logout.ho;\"><img src=\"resources/images/host/common/logout.png\"></a></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction goIndex(){\r\n");
      out.write("\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("/goIndex.ho\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</div>\r\n");
      out.write("\t<div id=\"aside\" class=\"table-secondary\">\r\n");
      out.write("\t\t<div id=\"triby-manage\">\r\n");
      out.write("  \t\t\t<div id=\"list-header\" class=\"card-header\">트리비 관리</div>\r\n");
      out.write(" \t\t\t <div class=\"card-body\">\r\n");
      out.write(" \t\t\t <ul class=\"none-bullet\">\r\n");
      out.write(" \t\t\t \t<li><a onclick=\"makeTriby();\">트리비 만들기</a></li>\r\n");
      out.write("\t\t\t \t<li><a onclick=\"myTriby();\">마이 트리비</a></li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"member-manage\">\r\n");
      out.write("\t\t\t<div id=\"list-header\" class=\"card-header\">멤버 관리</div>\r\n");
      out.write(" \t\t\t <div class=\"card-body\">\r\n");
      out.write(" \t\t\t <ul class=\"none-bullet\">\r\n");
      out.write(" \t\t\t \t<li><a onclick=\"manageQna();\">Q&A 관리</a></li>\r\n");
      out.write("\t\t\t \t<li><a onclick=\"manageRev();\">리뷰 관리</a></li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"calculate-manage\">\r\n");
      out.write("\t\t\t<div id=\"list-header\" class=\"card-header\">정산 센터</div>\r\n");
      out.write(" \t\t\t <div class=\"card-body\">\r\n");
      out.write(" \t\t\t <ul class=\"none-bullet\">\r\n");
      out.write(" \t\t\t \t<li><a onclick=\"manageCal();\">정산 관리</a></li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"manage-center\">\r\n");
      out.write("\t\t\t<div id=\"list-header\" class=\"card-header\">지원 센터</div>\r\n");
      out.write(" \t\t\t <div class=\"card-body\">\r\n");
      out.write(" \t\t\t <ul class=\"none-bullet\">\r\n");
      out.write(" \t\t\t \t<li><a onclick=\"goNotice();\">공지사항</a></li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction makeTriby(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( contextPath);
      out.write("/makeTriby.ho\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction myTriby(){\r\n");
      out.write("\t\t\t//location.href=\"");
      out.print( contextPath);
      out.write("/myTriby.ho?hno=\" + ");
      out.print( loginHost.getHost_no() );
      out.write(";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar form = document.createElement(\"form\");      // form생성\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.setAttribute(\"method\", \"post\");                    // method 설정\r\n");
      out.write("\t\t\tform.setAttribute(\"action\", \"");
      out.print( contextPath );
      out.write("/myTriby.ho\");       // action 설정\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.body.appendChild(form);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"name\", \"hNo\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"value\", ");
      out.print( loginHost.getHost_no() );
      out.write(");        //value 값 설정\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.appendChild(input_id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id2 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"name\", \"status\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"value\", 0);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id2);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id3 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"name\", \"page\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"value\", 1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id3);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction manageQna(){\r\n");
      out.write("\t\t\t//location.href=\"");
      out.print( contextPath);
      out.write("/manageQna.ho\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar form = document.createElement(\"form\");      // form생성\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.setAttribute(\"method\", \"post\");                    // method 설정\r\n");
      out.write("\t\t\tform.setAttribute(\"action\", \"");
      out.print( contextPath );
      out.write("/manageQna.ho\");       // action 설정\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tdocument.body.appendChild(form);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tvar input_id = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"name\", \"hNo\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"value\", ");
      out.print( loginHost.getHost_no() );
      out.write(");        //value 값 설정\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.appendChild(input_id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id2 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"name\", \"status\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"value\", 0);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id2);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id3 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"name\", \"page\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"value\", 1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id3);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tform.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction manageRev(){\r\n");
      out.write("\t\t\t//location.href=\"");
      out.print( contextPath);
      out.write("/manageRev.ho\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar form = document.createElement(\"form\");      // form생성\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.setAttribute(\"method\", \"post\");                    // method 설정\r\n");
      out.write("\t\t\tform.setAttribute(\"action\", \"");
      out.print( contextPath );
      out.write("/manageRev.ho\");       // action 설정\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tdocument.body.appendChild(form);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tvar input_id = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"name\", \"hNo\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"value\", ");
      out.print( loginHost.getHost_no() );
      out.write(");        //value 값 설정\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.appendChild(input_id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id2 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"name\", \"page\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"value\", 1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id2);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tform.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction manageCal(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( contextPath);
      out.write("/manageCal.ho\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction goNotice(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( contextPath);
      out.write("/listh.no\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');

	double avgPoint = loginHost.getAvgPoint();
	double qnaAnswer = loginHost.getQnaAnswer();
	if(Double.isNaN(avgPoint)) {
    	avgPoint = 0;
	}
	if(Double.isNaN(qnaAnswer)) {
		qnaAnswer = 0;
	}
	

      out.write("   \r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("\t<div id=\"div1\" class=\"card border-secondary\">\r\n");
      out.write("  <div id=\"card-body1\" class=\"card-body\">\r\n");
      out.write("  <div id=\"inform-modify\" onclick=\"myPage();\">회원정보수정</div>\r\n");
      out.write("   <h4 class=\"card-title\" style=\"clear:both;\">안녕하세요! ");
      out.print( loginHost.getHost_name() );
      out.write(" 호스트님</h4>\r\n");
      out.write("   <h4><p class=\"card-text\">");
      out.print( loginHost.getHost_sName() );
      out.write("</p></h4>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"div2\" class=\"card border-secondary\">\r\n");
      out.write("<div id=\"card-body2\" class=\"card-body\">\r\n");
      out.write("   <div id=\"notice-detail\" onclick=\"goNotice();\">더 보기</div>\r\n");
      out.write("   <div>공지사항</div>\r\n");
      out.write("   <div id=\"noticeTb\">\r\n");
      out.write("   \t\t<table id=\"noticeTbt\" class=\"table table-hover\">\r\n");
      out.write("</table> \r\n");
      out.write("   </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"div3\" class=\"card border-secondary\">\r\n");
      out.write("\t\t\t<div id=\"card-body3\" class=\"card-body\">\r\n");
      out.write("\t\t\t\t<table id=\"informTb\" height=\"100%\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"33%\">이번 달<br>신청 트리비\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"33%\">이번 달<br>호스트 취소\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"33%\">전체<br>신청 완료\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35%\">");
      out.print( loginHost.getThisMtriby() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>0</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print( loginHost.getAllTriby() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>전체 후기</td>\r\n");
      out.write("\t\t\t\t\t\t<td>평균 별점</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Q&A 응답률</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35%\">");
      out.print( loginHost.getReviewCount() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( String.format("%.2f", avgPoint));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print( String.format("%.2f", qnaAnswer));
      out.write("%</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<div id=\"div4\" class=\"card border-secondary\">\r\n");
      out.write("  <div id=\"card-body4\" class=\"card-body\">\r\n");
      out.write("\t<table id=\"calculateTb\" height=\"100%\" width=\"100%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>이번달 매출액</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( loginHost.getThisMsales() );
      out.write("원</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>전체 매출액</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( loginHost.getAllsales() );
      out.write("원</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction myPage(){\r\n");
      out.write("\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("/myPage.ho\";\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goNotice(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( contextPath);
      out.write("/listh.no\";\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"mnlist.no\",\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(list){\r\n");
      out.write("\t\t\t\tconsole.log(list);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar $noticeTb = $(\"#noticeTbt\");// <table></table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$noticeTb.html(\"\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.each(list, function(index, value){\r\n");
      out.write("\t\t\t\t\tvar $tr = $(\"<tr>\");\t// <tr> </tr>\r\n");
      out.write("\t\t\t\t\tvar $categoryTd = $(\"<td>\").text(value.nCategory).css({\"width\":\"70px\", \"height\":\"20px\", \"font-size\":\"15px\"}); // <td width=\"100px\">관리자</td>\r\n");
      out.write("\t\t\t\t\tvar $titleTd = $(\"<td>\").text(value.nTitle); // <td width=\"400px\">안녕하세여</td>\r\n");
      out.write("\t\t\t\t\tvar $dateTd = $(\"<td>\").text(value.nDate).css({\"font-size\":\"12px\", \"text-align\":\"right\", \"color\":\"gray\"}); // <td width=\"200px\">19년 10월 04일</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$tr.append($categoryTd);\r\n");
      out.write("\t\t\t\t\t$tr.append($titleTd);\r\n");
      out.write("\t\t\t\t\t$tr.append($dateTd);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$noticeTb.append($tr);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},error:function(){\r\n");
      out.write("\t\t\t\tconsole.log(\"통신 실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
