/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-16 02:45:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.host;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.triby.tImage.model.vo.Image;
import com.triby.triby.model.vo.Triby;
import com.triby.common.PageInfo;
import com.triby.host.model.vo.Host;

public final class myTriby_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/host/header.jsp", Long.valueOf(1570963706000L));
    _jspx_dependants.put("/views/host/aside.jsp", Long.valueOf(1570791286000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.triby.tImage.model.vo.Image");
    _jspx_imports_classes.add("com.triby.triby.model.vo.Triby");
    _jspx_imports_classes.add("com.triby.common.PageInfo");
    _jspx_imports_classes.add("com.triby.host.model.vo.Host");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	ArrayList<Triby> tList = (ArrayList<Triby>) request.getAttribute("tList");
	ArrayList<Image> iList = (ArrayList<Image>) request.getAttribute("iList");
	int status = (int) request.getAttribute("status");
	PageInfo pi = (PageInfo) request.getAttribute("pi");
	
	int currentPage = pi.getCurrentPage();
	int maxPage = pi.getMaxPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();

      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>myTriby</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t#wrap{\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\tmargin: 1%;\r\n");
      out.write("\t\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t\twidth:80%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#title{font-size:18px; font-weight:bold; margin-bottom:1rem;}\r\n");
      out.write("\t#content{width:100%; height: 77vh; margin: 0; padding:1rem 1rem 1rem 2rem; overflow-y: auto;}\r\n");
      out.write("\t#navArea{float:left;}\r\n");
      out.write("\t#article{height:100%}\r\n");
      out.write("\t#article .card-header{\r\n");
      out.write("\t\twidth:30%;\r\n");
      out.write("\t\theight:420px;\r\n");
      out.write("\t\tmargin-top:1rem; \r\n");
      out.write("\t\tmargin-bottom:1rem;\r\n");
      out.write("\t\tbackground:#F6F6F6;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\tmargin-left:1rem;\r\n");
      out.write("\t\tmargin-right:1rem;\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t.pagination{justify-content: center;}\r\n");
      out.write("\t#imgArea{height:180px;}\r\n");
      out.write("\t#contentArea{height:220px;}\r\n");
      out.write("\ttable{width:90%; margin-left:auto; margin-right:auto; font-size:16px;}\r\n");
      out.write("\t#contentTb tr td:nth-child(2){text-align:right;}\r\n");
      out.write("\t#btnTb{text-align:center; position: absolute; bottom:1%}\r\n");
      out.write("\ttd{height:30px;}\r\n");
      out.write("\th3{margin-left:3%;}\r\n");
      out.write("\t.btn:hover{cursor:pointer;}\r\n");
      out.write("\t#emptyArea{width:100%; text-align:center; padding-top:20%; height:100%;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
 String contextPath = request.getContextPath(); 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody{height:100%; overflow:auto;}\r\n");
      out.write("\t#aside{\r\n");
      out.write("\t\twidth:18%;\r\n");
      out.write("\t\theight:100vh;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\t#triby-manage, #member-manage{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.none-bullet{list-style-type: none;}\r\n");
      out.write("\tli{margin-top:10px;}\r\n");
      out.write("\tli a{\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t}\r\n");
      out.write("\tli a:hover{\r\n");
      out.write("\t\ttext-decoration:underline;\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#list-header{font-size:18px;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">");
      out.write('\r');
      out.write('\n');
 
	Host loginHost = (Host) session.getAttribute("loginHost");
	String joinSuccessMsg = (String)request.getAttribute("joinSuccessMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/popper.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/bootstrap.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar joinSuccessMsg = \"");
      out.print(joinSuccessMsg);
      out.write("\"\r\n");
      out.write("$(function(){\r\n");
      out.write("\tif(joinSuccessMsg!=\"null\"){\r\n");
      out.write("\talert(joinSuccessMsg);\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body{height:100%; overflow:hidden;}\r\n");
      out.write("\t#wrapper{\r\n");
      out.write("    height: 10%;\r\n");
      out.write("    overflow:hidden;\r\n");
      out.write("    font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t} \r\n");
      out.write("\t#logo-wrap{\r\n");
      out.write("\t\twidth:15%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logo{\r\n");
      out.write("\t\tmargin-left: auto;\r\n");
      out.write("\t\tmargin-right:auto;\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\theight:60px;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\tlabel{\r\n");
      out.write("\t\tmargin-left:1%;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\twidth:50%;\r\n");
      out.write("\t\tline-height: 50px;\r\n");
      out.write("\t\tmargin-top: auto;\r\n");
      out.write("\t\tmargin-bottom: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t#lb2{\r\n");
      out.write("\t\twidth:27%;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\ttext-align:right;\r\n");
      out.write("\t\tline-height: 50px;\r\n");
      out.write("\t\tmargin-right:1%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logout{\r\n");
      out.write("\t\tmargin-left:2%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logo:hover{cursor:pointer;}\r\n");
      out.write("</style>\r\n");
      out.write("<title>관리자 페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("<div id=\"header\" class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\r\n");
      out.write("  <div id=\"logo-wrap\"><div id=\"logo\" onclick=\"goIndex();\"><img src=\"resources/images/triby5.png\"></div></div>\r\n");
      out.write("  <label>호스트 관리페이지</label>\r\n");
      out.write("   <div id=\"lb2\">");
      out.print( loginHost.getHost_name() );
      out.write(" 호스트님 반갑습니다!</div>\r\n");
      out.write("  <div id=\"logout\"><a href=\"");
      out.print( request.getContextPath());
      out.write("/logout.ho;\"><img src=\"resources/images/host/common/logout.png\"></a></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction goIndex(){\r\n");
      out.write("\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("/goIndex.ho\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</div>\r\n");
      out.write("\t<div id=\"aside\" class=\"table-secondary\">\r\n");
      out.write("\t\t<div id=\"triby-manage\">\r\n");
      out.write("  \t\t\t<div id=\"list-header\" class=\"card-header\">트리비 관리</div>\r\n");
      out.write(" \t\t\t <div class=\"card-body\">\r\n");
      out.write(" \t\t\t <ul class=\"none-bullet\">\r\n");
      out.write(" \t\t\t \t<li><a onclick=\"makeTriby();\">트리비 만들기</a></li>\r\n");
      out.write("\t\t\t \t<li><a onclick=\"myTriby();\">마이 트리비</a></li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"member-manage\">\r\n");
      out.write("\t\t\t<div id=\"list-header\" class=\"card-header\">멤버 관리</div>\r\n");
      out.write(" \t\t\t <div class=\"card-body\">\r\n");
      out.write(" \t\t\t <ul class=\"none-bullet\">\r\n");
      out.write(" \t\t\t \t<li><a onclick=\"manageQna();\">Q&A 관리</a></li>\r\n");
      out.write("\t\t\t \t<li><a onclick=\"manageRev();\">리뷰 관리</a></li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"calculate-manage\">\r\n");
      out.write("\t\t\t<div id=\"list-header\" class=\"card-header\">정산 센터</div>\r\n");
      out.write(" \t\t\t <div class=\"card-body\">\r\n");
      out.write(" \t\t\t <ul class=\"none-bullet\">\r\n");
      out.write(" \t\t\t \t<li><a onclick=\"manageCal();\">정산 관리</a></li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"manage-center\">\r\n");
      out.write("\t\t\t<div id=\"list-header\" class=\"card-header\">지원 센터</div>\r\n");
      out.write(" \t\t\t <div class=\"card-body\">\r\n");
      out.write(" \t\t\t <ul class=\"none-bullet\">\r\n");
      out.write(" \t\t\t \t<li><a onclick=\"goNotice();\">공지사항</a></li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction makeTriby(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( contextPath);
      out.write("/makeTriby.ho\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction myTriby(){\r\n");
      out.write("\t\t\t//location.href=\"");
      out.print( contextPath);
      out.write("/myTriby.ho?hno=\" + ");
      out.print( loginHost.getHost_no() );
      out.write(";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar form = document.createElement(\"form\");      // form생성\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.setAttribute(\"method\", \"post\");                    // method 설정\r\n");
      out.write("\t\t\tform.setAttribute(\"action\", \"");
      out.print( contextPath );
      out.write("/myTriby.ho\");       // action 설정\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.body.appendChild(form);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"name\", \"hNo\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"value\", ");
      out.print( loginHost.getHost_no() );
      out.write(");        //value 값 설정\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.appendChild(input_id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id2 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"name\", \"status\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"value\", 0);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id2);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id3 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"name\", \"page\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"value\", 1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id3);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction manageQna(){\r\n");
      out.write("\t\t\t//location.href=\"");
      out.print( contextPath);
      out.write("/manageQna.ho\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar form = document.createElement(\"form\");      // form생성\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.setAttribute(\"method\", \"post\");                    // method 설정\r\n");
      out.write("\t\t\tform.setAttribute(\"action\", \"");
      out.print( contextPath );
      out.write("/manageQna.ho\");       // action 설정\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tdocument.body.appendChild(form);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tvar input_id = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"name\", \"hNo\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"value\", ");
      out.print( loginHost.getHost_no() );
      out.write(");        //value 값 설정\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.appendChild(input_id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id2 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"name\", \"status\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"value\", 0);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id2);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id3 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"name\", \"page\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"value\", 1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id3);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tform.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction manageRev(){\r\n");
      out.write("\t\t\t//location.href=\"");
      out.print( contextPath);
      out.write("/manageRev.ho\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar form = document.createElement(\"form\");      // form생성\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.setAttribute(\"method\", \"post\");                    // method 설정\r\n");
      out.write("\t\t\tform.setAttribute(\"action\", \"");
      out.print( contextPath );
      out.write("/manageRev.ho\");       // action 설정\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tdocument.body.appendChild(form);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tvar input_id = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"name\", \"hNo\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"value\", ");
      out.print( loginHost.getHost_no() );
      out.write(");        //value 값 설정\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.appendChild(input_id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id2 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"name\", \"page\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"value\", 1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id2);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tform.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction manageCal(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( contextPath);
      out.write("/manageCal.ho\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction goNotice(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( contextPath);
      out.write("/listh.no\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t<div id=\"title\">마이 트리비</div>\r\n");
      out.write("\t<div id=\"content\" class=\"jumbotron\">\r\n");
      out.write("\t\t<div id=\"top\">\r\n");
      out.write("\t<div id=\"navArea\">\r\n");
      out.write("\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t  \r\n");
 if(status == 0) { 
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link active\" data-toggle=\"tab\" id=\"ing\" onclick=\"change(0, 1);\">판매중</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\" data-toggle=\"tab\" id=\"wait\" onclick=\"change(1, 1);\">대기</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\" data-toggle=\"tab\" id=\"end\" onclick=\"change(2, 1);\">종료</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\r\n");
 } else if(status == 1) { 
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("    <a class=\"nav-link\" data-toggle=\"tab\" id=\"ing\" onclick=\"change(0, 1);\">판매중</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link active\" data-toggle=\"tab\" id=\"wait\" onclick=\"change(1, 1);\">대기</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\" data-toggle=\"tab\" id=\"end\" onclick=\"change(2, 1);\">종료</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\r\n");
} else {
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("    <a class=\"nav-link\" data-toggle=\"tab\" id=\"ing\" onclick=\"change(0, 1);\">판매중</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\" data-toggle=\"tab\" id=\"wait\" onclick=\"change(1, 1);\">대기</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link active\" data-toggle=\"tab\" id=\"end\" onclick=\"change(2, 1);\">종료</a>\r\n");
      out.write("\t\t  </li>\r\n");
 } 
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br style=\"clear:both\">\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div id=\"article\">\r\n");
      out.write("\t");
 if(tList.isEmpty()) { 
      out.write("\r\n");
      out.write("\t\t<div id=\"emptyArea\"><h2>트리비가 없습니다ㅠ^ㅠ</h2></div>\r\n");
      out.write("\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t");
for(int i=0; i<tList.size(); i++) { 
      out.write("\r\n");
      out.write("\t\t\t<div id=\"div1\" class=\"card-header\">\r\n");
      out.write("\t\t<div id=\"imgArea\"><img src=\"");
      out.print(contextPath );
      out.write("/resources/images/triby/");
      out.print(iList.get(i).getiName() );
      out.write("\" width=\"100%\" height=\"100%\"></div>\r\n");
      out.write("\t\t<div id=\"contentArea\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<h3>");
      out.print( tList.get(i).gettTitle() );
      out.write("</h3> <br>\r\n");
      out.write("\t\t<table id=\"contentTb\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>상태</td>\t\r\n");
      out.write("\t\t\t\t<td>");
 if(tList.get(i).getAppoval_status().equals("Y")) { 
      out.write("\r\n");
      out.write("\t\t\t\t판매중\r\n");
      out.write("\t\t\t\t");
 } else if(tList.get(i).getAppoval_status().equals("N")) { 
      out.write("\r\n");
      out.write("\t\t\t\t대기\r\n");
      out.write("\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t종료\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>가격</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( tList.get(i).gettPrice() );
      out.write(" 원</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table id=\"btnTb\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><form method=\"post\" action=\"");
      out.print( contextPath);
      out.write("/insertForm.op\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"tNo\" value=\"");
      out.print( tList.get(i).gettNo() );
      out.write("\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-info\" type=\"submit\">옵션 추가</button>\r\n");
      out.write("\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t\t<td><form method=\"post\" action=\"");
      out.print( contextPath);
      out.write("/select.op\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"tNo\" value=\"");
      out.print( tList.get(i).gettNo() );
      out.write("\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-info\">옵션 관리</button>\r\n");
      out.write("\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t\t<td><form method=\"post\" action=\"");
      out.print( contextPath);
      out.write("/updateForm.tr\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"tNo\" value=\"");
      out.print( tList.get(i).gettNo() );
      out.write("\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-info\" type=\"submit\">내용 수정</button></form></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t<br style=\"clear:both\">\r\n");
      out.write("\t\t\t<div id=\"pageArea\"> <ul class=\"pagination pagination-sm\">\r\n");
      out.write("    ");
 if(currentPage <= 5) { 
      out.write("\r\n");
      out.write("\t\t<li class=\"page-item disabled\">\r\n");
      out.write("     \t <a class=\"page-link\" href=\"#\">&laquo;</a>\r\n");
      out.write("    \t</li>\r\n");
      out.write("\t");
} else { 
      out.write("\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("     \t <a class=\"page-link\" onclick=\"change(");
      out.print( status );
      out.write(',');
      out.write(' ');
      out.print( startPage-1 );
      out.write(");\">&laquo;</a>\r\n");
      out.write("    \t</li>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("    ");
 for(int p = startPage; p<=endPage; p++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 if(p == currentPage) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item active\"><a class=\"page-link\">");
      out.print( p );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" onclick=\"change(");
      out.print( status );
      out.write(',');
      out.write(' ');
      out.print( p );
      out.write(");\">");
      out.print( p );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
 if(startPage > maxPage -5) { 
      out.write("\t\t\r\n");
      out.write("\t\t<li class=\"page-item disabled\">\r\n");
      out.write("     \t <a class=\"page-link\" href=\"#\">&raquo;</a>\r\n");
      out.write("    \t</li>\r\n");
      out.write("\t");
} else { 
      out.write("\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("      <a class=\"page-link\" onclick=\"change(");
      out.print( status );
      out.write(',');
      out.write(' ');
      out.print( endPage +1);
      out.write(");\">&raquo;</a>\r\n");
      out.write("    \t</li>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("  </ul></div>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction change(status, page){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar hNo = ");
      out.print( loginHost.getHost_no() );
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar form = document.createElement(\"form\");      // form생성\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.setAttribute(\"method\", \"post\");                    // method 설정\r\n");
      out.write("\t\t\tform.setAttribute(\"action\", \"");
      out.print( contextPath );
      out.write("/myTriby.ho\");       // action 설정\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.body.appendChild(form);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"name\", \"hNo\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id.setAttribute(\"value\", hNo);        //value 값 설정\r\n");
      out.write("\r\n");
      out.write("\t\t\tform.appendChild(input_id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id2 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"name\", \"status\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id2.setAttribute(\"value\", status);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id2);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar input_id3 = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"name\", \"page\");      //name 속성 지정\r\n");
      out.write("\t\t\tinput_id3.setAttribute(\"value\", page);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.appendChild(input_id3);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tform.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
